train:
    _target_: src.datasets.LibrispeechDataset
    part: "train-clean-100"
    max_audio_length: 5.0
    max_text_length: 100
    limit: 1
    instance_transforms: ${transforms.instance_transforms.train}
val:
    _target_: src.datasets.LibrispeechDataset
    part: "dev-clean"
    max_audio_length: 5.0
    max_text_length: 50
    limit: 10
    instance_transforms: ${transforms.instance_transforms.inference}
test:
    _target_: src.datasets.LibrispeechDataset
    part: "test-clean"
    max_audio_length: 5.0
    max_text_length: 50
    limit: 10
    instance_transforms: ${transforms.instance_transforms.inference}
