defaults:
    - model: deepspeech2
    - metrics: example
    - datasets: eval
    - dataloader: example
    - transforms: example_only_instance
    - _self_
text_encoder:
    _target_: src.text_encoder.CTCTextEncoder
inferencer:
    device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
    device: auto # device name or "auto"
    save_path: "deepspeech2_inference" # any name here, can be a dataset name
    seed: 42
    from_pretrained: "model_best.pth" # path to the pretrained model
